# adapted from https://github.com/XavierCHEN34/ClickSEG/blob/main/config.yml

EXPS_PATH: "./Back-End/FocalClick/finetuning/experiments"

# TODO: adapt this and mention in README
COCO_PATH: "/exp/red_globe_2021_07-27_09-06_train_val"
SEGFORMER_B3: "/exp/SEMI-AUTOMATIC-SEGMENTATION-TOOL/Back-End/FocalClick/models/focalclick/segformerB3_S2_comb.pth"
