# adapted from https://github.com/XavierCHEN34/ClickSEG/blob/main/config.yml

EXPS_PATH: "/exp/SEMI-AUTOMATIC-SEGMENTATION-TOOL//Back-End/FocalClick/finetuning/experiments"

REG_GLOBE_TRAIN_VAL: "/exp/red_globe_2021_07-27_09-06_train_val"
RED_GLOBE_TRAIN_TEST: "/exp/red_globe_2021_07-27_09-06_train_test"
WGISD : "/exp/wgisd"
SEGFORMER_B3: "/exp/SEMI-AUTOMATIC-SEGMENTATION-TOOL/Back-End/FocalClick/models/focalclick/segformerB3_S2_comb.pth"

# paths for checkpoints, visualizations, and logs during training
CHECKPOINTS_PATH: "/exp/SEMI-AUTOMATIC-SEGMENTATION-TOOL/Back-End/FocalClick/finetuning/checkpoints"
VIS_PATH: "/exp/SEMI-AUTOMATIC-SEGMENTATION-TOOL/Back-End/FocalClick/finetuning/visualization"
LOGS_PATH: "/exp/SEMI-AUTOMATIC-SEGMENTATION-TOOL/Back-End/FocalClick/finetuning/experiments/logs"

# paths for visualizations and summary of hyperparameter search
# about the actual training
OPTUNA_VIS_PATH: "/exp/SEMI-AUTOMATIC-SEGMENTATION-TOOL/Back-End/FocalClick/finetuning/optuna/visualization"
OPTUNA_SUM_PATH: "/exp/SEMI-AUTOMATIC-SEGMENTATION-TOOL/Back-End/FocalClick/finetuning/optuna/summary"